<?php
namespace Modules\V1\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Route;
use rjapi\extension\BaseController;

class DefaultController extends BaseController 
{
    public function __construct(Route $route)
    {
        parent::__construct($route);
    }

    public function index(Request $request)
    {
        parent::index($request); // TODO: Change the autogenerated stub
    }
}
